<a href="https://colab.research.google.com/github/valentinacorreazta-pixel/Anal-tica-de-Negocios-/blob/main/1_Naive_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Caso de estudio**
En este documento se desarrolla y analiza un modelo Naive Bayes para la PreAprobación de créditos en una entidad financiera utilizandi las variables socioeconomicas de un solicitante de crédito. De acuerdo con lo anterior las variables socieconomicas son:
**Edad**: es la edad que posee el solicitante de credito al momento de solicitar un credito.
**Ingresos**: Ingresos recibidos por una persona como resultado de una actividad comercial.
**Egresos**: Son los gastos mensuales del solicitante. Gastos de personas a crago, hijos y servicios publicos.
**Monto (EAD)**: Indica el dinero que una persona solicita a una entidad financiera como crédito.

0. Se procede con la carga de las librerias de trabajo






In [ ]:
import numpy as np #libreria numerica por excelencia
import pandas as pd #Libreria para la comunicación con archivo de excel

#librerias especificas
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix

1. se cargan los datos de trabajo de la base de datos BaseAAA

In [ ]:
nxl='/content/datos.xlsx'
XDB=pd.read_excel(nxl,sheet_name=1)
#XDB.head(100) este es para mostrar la base de datos cargada y esta filas son los numeros de la cantidad de valores que quiero ver


# seleccionamo las variables del trabajo
XD=XDB[['Edad','Ingresos','Egresos','Monto (EAD)']]  #Variables de Trabajo, tienen que estar escritas tal cual el excel
XD.head(10)
yd=XDB[['PreApr']] #Esta la variable de decisión
yd.head()




,PreApr
0,1
1,1
2,0
3,1
4,1


2. Implementamos Modelo de Naive Bayes



In [ ]:
mnb=GaussianNB()
mnb.fit(XD,yd)   #Ajustar Variables Entrada - Salida

#Mostramos las medias de las variables
u=mnb.theta_
sigma=mnb.var_;sigma=np.sqrt(sigma)
print("'Edad','Ingresos','Egresos','Monto (EAD)'")
print(u)
print("Las desviaciones son:")
print(sigma)

'Edad','Ingresos','Egresos','Monto (EAD)'
[[  40.98411626  431.42680644  401.54995644  289.41445941]
 [  41.10752688 1029.98947251  900.19312144  781.2021157 ]]
Las desviaciones son:
[[ 12.21303268 325.79791497 342.77286087 235.95783541]
 [ 12.25106493 472.43342807 525.43337837 469.90038088]]


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


**Análisis de Resultados**
De los resultados arroajdos por el modelo, podemos observar que la categoría de PreAprobados posee ingresos superiores a las categroias de PreNegados, esto indica claramente la predominancia de la variable para aporbar creditos. Es importante mencionar que la edad es mayor para los PreAprobados que para los PreNegados, lo que sognifica que el banco busca perosnas con mayor experiencias crediticia. Podemos decir igualmente que los PreAporbados, tienen egresos superiores a los de la categoria de PreNegados, sin embargo, los PreAprobados estna solicitando montos superiores a los de la categoría de PreNegados, esto es un indicador de la capacidad de este grupo para hacer frente a un crédito.

3. Se procede con la evaluación del modelo. Para la evaluación de este tipo de modelo se utiliza la matriz de confución

In [ ]:
ydp=mnb.predict(XD) #Esto es lo que el modelo aprende-ydp de pronostico
cm=confusion_matrix(yd,ydp)
print(cm)
# lo que arroja es el desmepeño del modelo
#se determinan las metricas de la matriz de confusión

VN=cm[0,0];FP=cm[0,1];FN=cm[1,0];VP=cm[1,1];TDatos=len(XDB)

#1. Exactitud: funcionamiento general del modelo
Ex=(VP+VN)/TDatos
print("Exactitud: ",Ex)

#2 ESE 0,76 es la tasa de error: %Fallos del modelo, el modelo es bueno porque ninguno es perfecrto y aprtir de 75% es buen modelo
TEr=(FP+FN)/TDatos
print("tasa Error: ",TEr)


#3 Sensibilidad: Como se comporto con respecto a los positivos solamente
Se=VP/(VP+FN)
print("sensibilidad: ",Se)

#4 especificidad: como se comporta pronosticando negativos
Es=VN/(VN+FP)
print("Especificidad: ",Es)

#5 Precisión: es una version de como se comporta el modelo frente a los positivos solamente (es la columna del 1)
Pr=VP/(VP+FP)
print("Precisión: ",Pr)

#6 Predicción Negativa: Como funciona el modelo pronósticando creditos PreNegados
PrN=VN/(VN+FN)
print("Predicción Negativa: ",PrN)

[[2502  457]
 [ 937 1946]]
Exactitud:  0.7613830879835672
tasa Error:  0.23861691201643273
sensibilidad:  0.6749913284772806
Especificidad:  0.8455559310577898
Precisión:  0.8098210570120683
Predicción Negativa:  0.7275370747310265


**Evaluación del Modelo**
Análisis de Resultados De acuerdo con los r4esultados, podemos observar de manera general que el modelo alcanzó una exactitud por encima del 75% en promedio, lo que indica el buen comportamiento del modelo frente a la clasificación de los solicitantes de crédito frente a la PreApr y la PreNegación. Se destaca la precisión con un 80.9%, lo que indica el buen funcionamiento del modelo frente a la PreAprobación de créditos. Igualmente se puede observar el buen comportamineto del modelo frente a la PreNegación de créditos, tal y como lo demuestra el indice de especificidad del modelo, el cual estuvo por encima del 84% en promedio. Es importante mencionar que la excatitud queda por debajo del 80% ya ue está métrica se ve afectada por los errores en la clasificación de solicitantes de crédito, lo que se evidencia a tráves de la Sensibilidad y la Predicción Negativa.

4. Evaluamos un solicitante (ejm)

In [ ]:
XP=[34,1500,800,1000]
ydc=mnb.predict([XP])
print(ydc)

if ydc==1:
  print("El solicitante es PreAprobado")
else:
  print("El solicitante es Negado")

[1]
El solicitante es PreAprobado


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(
